# Simple Linear Regression

In [2]:
#Name:Sejal Vitthal Chavhan
#RolL no. :21
#Sub : ET 1
#section:3A
#Date:16/10/2024


In [8]:
# Aim: To Perform Simple Linear Regression

In [9]:
import pandas as pd

In [10]:
import os

In [11]:
os.chdir("C:\\Users\\91957\\OneDrive\\Desktop")

In [12]:
df=pd.read_csv("Salary_Dataset.csv")

In [13]:
df.head(10)

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
5              2.9   56642
6              3.0   60150
7              3.2   54445
8              3.2   64445
9              3.7   57189

In [14]:
df.tail()

YearsExperience  Salary
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes


In [16]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [17]:
df.shape

(30, 2)

In [18]:
df.size

60

In [19]:
df.ndim

2

In [22]:
df.isnull()

YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False

In [23]:
df.isnull().any()

YearsExperience    False
Salary             False
dtype: bool

In [24]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [29]:
a="Sejal"

In [30]:
print(a)

Sejal


In [31]:
a[0]

'S'

In [32]:
a[-1]

'l'

In [33]:
a[1:3]

'ej'

In [34]:
a[1:4]

'eja'

In [35]:
#Assiging values in X & Y
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values



#X = df['YearsExperience']
#y = df['Salary']

In [36]:
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [37]:
print(y)

[ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872]


In [38]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [39]:
#Splitting testdata into X_train,X_test,y_train,y_test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,random_state=42) 

In [40]:
print(X_train)

[[ 1.1]
 [ 2.2]
 [ 5.1]
 [ 2.9]
 [ 4.1]
 [ 4. ]
 [ 7.9]
 [ 1.3]
 [ 1.5]
 [ 9. ]
 [ 2. ]
 [ 7.1]
 [ 9.5]
 [ 5.9]
 [10.5]
 [ 6.8]
 [ 3.2]
 [ 3.9]
 [ 4.5]
 [ 6. ]
 [ 3. ]]


In [41]:
print(X_test)

[[ 9.6]
 [ 4.9]
 [ 8.2]
 [ 5.3]
 [ 3.2]
 [ 3.7]
 [10.3]
 [ 8.7]
 [ 4. ]]


In [42]:
print(y_train)

[ 39343  39891  66029  56642  57081  55794 101302  46205  37731 105582
  43525  98273 116969  81363 121872  91738  54445  63218  61111  93940
  60150]


In [43]:
print(y_test)

[112635  67938 113812  83088  64445  57189 122391 109431  56957]


In [44]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [45]:
#Assigning Coefficient (slope) to m
m = lr.coef_  

In [46]:
print("Coefficient  :" , m)

Coefficient  : [9339.08172382]


In [47]:
#Assigning Y-intercept to a
c = lr.intercept_

In [48]:
print("Intercept : ", c)

Intercept :  25918.438334893202


In [49]:
lr.score(X_test,y_test) * 100

94.14466227178214